### ISSUE TITLE
cv2.error: /home/yi/opencv-2.4.11/modules/imgproc/src/color.cpp:3739: error: (-215) scn == 3 || scn == 4 in function cvtColor

### ISSUE THREAD

**Issue by yichenlin199** [WillBrennan/ImageStitching#3]
my opencv version 2.4.11, numpy version python 1.12.1
exe: python image_stitching.py image/phantom3-ieu/  --display --save
then:
INFO:root:beginning sequential matching
('image_path', 'image/phantom3-ieu/')
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/yi/opencv-2.4.11/modules/imgproc/src/color.cpp, line 3739
Traceback (most recent call last):
  File "image_stitching.py", line 54, in <module>
    image_gray = cv2.cvtColor(image_colour, cv2.COLOR_RGB2GRAY)
cv2.error: /home/yi/opencv-2.4.11/modules/imgproc/src/color.cpp:3739: error: (-215) scn == 3 || scn == 4 in function cvtColor

**Comment by WillBrennan** [comment]
Hey - Sorry for the late reply!

This is where I changed the argument style to receive a list of pictures rather than a directory but I forgot to update the readme. I've added back in the old command style, #4,  (as in the readme) so it should now work for you. 

I've also added some extra logging, for large images computing the features can take about 10 seconds.
